### ISSUE TITLE
Question: Only allowing specific users to access AZStartStop web

### ISSUE THREAD

**Issue by harryvek** [sg3-141-592/AzStartStop#12]
I've set-up AAD authentication, but wanted to know how access can be granted for only specific groups/users. I don't want all our AAD users to be able to access the web portal for obvious security reasons.

Thanks in advance.

**Comment by sg3-141-592** [comment]
Hey @harryvek ,

I don't have Active Directory Premium on my Azure subscription to test it, but I think you need to setup a Conditional Access policy against the Enterprise Application Object in AD to limit access to users in a particular group.

<img width="741" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/efb525d6-a022-46d2-908b-bba6b4b4f86d">

In the meanwhile I've added #14 to give people some initial authentication instructions.

**Comment by harryvek** [comment]
Thanks for tip, I did originally try that but my mistake was I should have used 2 conditional access policies (block/deny) rather than just the one.
