### ISSUE TITLE
GBP Symbol doesn't update when currency is changed

### ISSUE THREAD

**Issue by JClarke90** [sg3-141-592/AzStartStop#3]
Sorry I promise I'll not post too many things, but I really like the tool, just what I've been looking for.

Hopefully a quick fix, when you select the currency the table updates but the total still shows the GBP symbol instead of the selected currency. But at least the amount is correct so not a big issue.

![image](https://github.com/sg3-141-592/AzStartStop/assets/12259768/fe5ecc37-5cd1-426e-8c79-89c9cb51663e)

**Comment by sg3-141-592** [comment]
Hey @JClarke90 no worries, feel free to raise anything that isn't working or would make it even more useful for you. Good spot, so on this table there's a little bit more work to do.

- VM Spend - last month - at the moment the currency for this value is based on the first billing currency for a VM we see in your subscription. For example we use GBP on this bill

<img width="296" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/bc4cbd53-f26f-4511-9824-f798d206b7ae">

- VM Spend - est next month - this should be in the currency users have selected in the background. I'll include it in a future release.

**Comment by JClarke90** [comment]
Ah interesting, makes sense as I’m just testing this on my msdn subscription so don’t really do much with the billing side. 

Will be testing it out in a dev environment this week so it should be correct in there.

Feel free to close this if it’s working as expected.

**Comment by sg3-141-592** [comment]
Fix has been pushed in #10 . Currency you select in settings is now used in your estimate.

<img width="550" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/0b8a61f8-c244-40a8-b484-15aaea5e3882">
