### ISSUE TITLE
Improve Storage Account setup in ARM Template

### ISSUE THREAD

**Issue by sg3-141-592** [sg3-141-592/AzStartStop#8]
> Some other questions concerning the related storage account:
> 
> Is there a specific reason for it being v1?
> <img width="593" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/c0c4cf26-7b07-415e-bd49-d36cab608524">
> 
> Is Blob anonymous access required? Is storage account key access required?
> <img width="176" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/9b5eb9e6-1fca-45bb-907c-088a42c821b4">
> 
> Can we increase TLS version without issues?
> <img width="134" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/2eb24a0a-c445-43a1-a61d-956ad77edca0">
> 
> _Originally posted by @gjongeneel in https://github.com/sg3-141-592/AzStartStop/issues/4#issuecomment-1726038776_
>

**Comment by sg3-141-592** [comment]
Hey @gjongeneel just pushed a fix in the ARM Templates. You'll need to redeploy to get the updated setup.

<img width="626" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/bea0feb6-fce7-4dd6-8728-ef06d9a444f4">

It seems like you can theoretically disable the Shared Key Access on the storage account, if you setup appropriate Managed Identity permissions elsewhere. But it'd add more complexity to the setup on-top of the additional Managed Identity Permissions users already have to setup so I'm going to avoid for now.

<img width="310" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/e82e6c48-1674-479f-ba61-76132357e6a7">

**Comment by gjongeneel** [comment]
Nice work & completely agree!
